project:
  type: website
  output-dir: docs

website:
  title: "Python Best Practices"
  navbar:
    background: primary
    left:
      - coding-standards/index.qmd
      - documentation/index.qmd
      - testing/index.qmd
      - reproducibility/index.qmd
  sidebar:
    contents:
      - text: "Python Best Practices"
        href: index.qmd
      - section: "Coding Standards"
        href: coding-standards/index.qmd
        contents:
          - coding-standards/coding-style.qmd
          - coding-standards/recommended-packages.qmd
          - coding-standards/factoring.qmd
          - coding-standards/recommended-packages.qmd
          - coding-standards/design-patterns.qmd
          - coding-standards/project-structure.qmd
      - section: "Documentation"
        href: documentation/index.qmd
        contents:
          - documentation/markdown.qmd
          - documentation/readme.qmd
          - documentation/docstrings.qmd
          - documentation/process-scripts.qmd
          - documentation/projects.qmd
          - documentation/changelog.qmd
      - section: "Testing"
        href: testing/index.qmd
        contents:
          - testing/manual-tests.qmd
          - testing/document-test-process.qmd
          - testing/coded-tests.qmd
          - testing/test-reports.qmd
          - testing/test-coverage.qmd
          - testing/validate-inputs.qmd

format:
  html:
    theme: bootstrap
    toc: true
